const categories = [
  {
    name: 'Starters',
    description: 'Crispy, smoky and appetizing Indian & Tandoori appetizers to kickstart your feast.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Main Course',
    description: 'Rich curries, slow-simmered gravies and freshly baked tandoori breads.',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Biryani',
    description: 'Fragrant basmati rice cooked on slow dum with aromatic spices and saffron.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Chinese',
    description: 'Wok-tossed Indo-Chinese favorites with zesty garlic, ginger and sauces.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Desserts',
    description: 'Decadent sweet endings crafted with pure ghee, saffron, and nuts.',
    image: 'https://images.unsplash.com/photo-1589119908995-c6837fa14d48?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Beverages',
    description: 'Authentic South Indian filter coffee, thick lassis, and refreshing coolers.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
  },
];

const foods = [
  // ==========================================
  // --- 1. STARTERS (11 DISHES) ---
  // ==========================================
  {
    name: 'Chicken Ghee Roast',
    description: 'Legendary Mangalorean delicacy cooked in pure clarified ghee with fiery red Byadgi chillies and whole spices.',
    price: 340,
    category: 'Starters',
    image: '/images/foods/chicken-ghee-roast.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Spicy',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Paneer Tikka Angara',
    description: 'Cubes of fresh cottage cheese marinated in hung curd, Kashmiri paprika, and smoked to perfection in clay oven.',
    price: 260,
    category: 'Starters',
    image: '/images/foods/paneer-tikka-angara.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Crispy Corn Pepper Salt',
    description: 'Golden sweet corn kernels tossed with crushed black peppercorns, scallions, garlic, and fresh green chillies.',
    price: 210,
    category: 'Starters',
    image: '/images/foods/crispy-corn-pepper-salt.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.5,
  },
  {
    name: 'Tandoori Murgh (Half)',
    description: 'Classic spring chicken tenderized in aromatic mustard oil and roasted over charcoal in an earthen tandoor.',
    price: 280,
    category: 'Starters',
    image: '/images/foods/tandoori-murgh-half.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.7,
  },
  {
    name: 'Hara Bhara Kebab',
    description: 'Crispy pan-seared patties of spinach, green peas, mashed potatoes, and roasted gram flour filled with cashew.',
    price: 220,
    category: 'Starters',
    image: '/images/foods/hara-bhara-kebab.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.6,
  },
  {
    name: 'Mutton Galouti Kebab',
    description: 'Melt-in-mouth royal Lucknowi minced lamb kebabs infused with 24 aromatic pot spices and smoked with cloves.',
    price: 380,
    category: 'Starters',
    image: '/images/foods/mutton-galouti-kebab.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Dahi Ke Kebab',
    description: 'Silky hung yogurt patties stuffed with chopped bell peppers, fresh coriander, and mint, pan-fried to crisp perfection.',
    price: 240,
    category: 'Starters',
    image: '/images/foods/dahi-ke-kebab.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.7,
  },
  {
    name: 'Fish Amritsari Fry',
    description: 'Crispy boneless sole fish fillets coated in carom seed (ajwain) spiced gram flour batter and deep fried to golden crunch.',
    price: 360,
    category: 'Starters',
    image: '/images/foods/fish-amritsari-fry.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Spicy',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Tandoori Malai Broccoli',
    description: 'Tender broccoli florets marinated in cardamom cream, melted cheese, and hung curd, gently chargrilled.',
    price: 270,
    category: 'Starters',
    image: '/images/foods/tandoori-malai-broccoli.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.6,
  },
  {
    name: 'Chicken 65 Bangalore Style',
    description: 'Crisp chicken bites tossed with tempered curry leaves, slit green chillies, crushed garlic, and tangy curd masala.',
    price: 290,
    category: 'Starters',
    image: '/images/foods/chicken-65-bangalore-style.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Spicy',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Mushroom Kurkure',
    description: 'Whole button mushrooms stuffed with spiced cheese, herb mix, coated in crunchy papad crumb and crisp fried.',
    price: 230,
    category: 'Starters',
    image: '/images/foods/mushroom-kurkure.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Medium',
    isPopular: false,
    rating: 4.6,
  },

  // ==========================================
  // --- 2. MAIN COURSE (12 DISHES) ---
  // ==========================================
  {
    name: 'Old Delhi Butter Chicken',
    description: 'Smoked tandoori chicken cooked in a velvety, buttery tomato gravy infused with dried fenugreek leaves (kasoori methi).',
    price: 360,
    category: 'Main Course',
    image: '/images/foods/old-delhi-butter-chicken.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Paneer Butter Masala',
    description: 'Soft cottage cheese simmered in a luscious cashew-onion-tomato makhani gravy enriched with butter and cream.',
    price: 310,
    category: 'Main Course',
    image: '/images/foods/paneer-butter-masala.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Bangalore Mutton Sukka Curry',
    description: 'Tender lamb chunks slow-cooked with fresh roasted coconut paste, curry leaves, and regional Bangalore spices.',
    price: 420,
    category: 'Main Course',
    image: '/images/foods/bangalore-mutton-sukka-curry.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Spicy',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Dal Makhani Royal',
    description: 'Overnight slow-cooked black lentils and kidney beans enriched with white butter, cream, and subtle smoky aroma.',
    price: 250,
    category: 'Main Course',
    image: '/images/foods/dal-makhani-royal.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.7,
  },
  {
    name: 'Butter Garlic Naan (2 pcs)',
    description: 'Leavened soft flatbread baked on tandoor walls, generously brushed with salted butter and minced fresh garlic.',
    price: 90,
    category: 'Main Course',
    image: '/images/foods/butter-garlic-naan-2-pcs.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.8,
  },
  {
    name: 'Kadhai Paneer Dhaba Style',
    description: 'Cottage cheese cubes and crunchy bell peppers tossed in an iron wok with freshly pounded coriander seeds and red chillies.',
    price: 290,
    category: 'Main Course',
    image: '/images/foods/kadhai-paneer-dhaba-style.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Spicy',
    isPopular: true,
    rating: 4.7,
  },
  {
    name: 'Chicken Tikka Masala',
    description: 'Charcoal-grilled juicy boneless chicken tikka simmered in a robust, spiced tomato-onion and cream gravy.',
    price: 350,
    category: 'Main Course',
    image: '/images/foods/chicken-tikka-masala.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Malai Kofta Imperial',
    description: 'Velvety cottage cheese and dry fruit dumplings swimming in a smooth cashew-saffron reduction with rose water hints.',
    price: 310,
    category: 'Main Course',
    image: '/images/foods/malai-kofta-imperial.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Mutton Rogan Josh',
    description: 'Authentic Kashmiri braised lamb simmered in gravy flavored with aromatic shallots, fennel seeds, ginger, and Kashmiri chillies.',
    price: 430,
    category: 'Main Course',
    image: '/images/foods/mutton-rogan-josh.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Yellow Dal Tadka Double Chaunk',
    description: 'Home-style yellow toor lentils tempered twice with clarified desi ghee, hing, cumin seeds, garlic, and dry Kashmiri chillies.',
    price: 210,
    category: 'Main Course',
    image: '/images/foods/yellow-dal-tadka-double-chaunk.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Medium',
    isPopular: false,
    rating: 4.6,
  },
  {
    name: 'Palak Paneer Lahsuni',
    description: 'Fresh organic spinach purée simmered with tender paneer cubes and finished with golden crispy garlic flakes.',
    price: 280,
    category: 'Main Course',
    image: '/images/foods/palak-paneer-lahsuni.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.7,
  },
  {
    name: 'Amritsari Kulcha with Chole',
    description: 'Spiced potato and paneer stuffed crusty tandoor flatbread served with slow-simmered Punjabi pindi chole and pickle.',
    price: 240,
    category: 'Main Course',
    image: '/images/foods/amritsari-kulcha-with-chole.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.8,
  },

  // ==========================================
  // --- 3. BIRYANI (10 DISHES) ---
  // ==========================================
  {
    name: 'Hyderabadi Dum Chicken Biryani',
    description: 'Fragrant long-grain aged Basmati rice layered with spiced marinated chicken, saffron milk, fried onions, and fresh mint.',
    price: 320,
    category: 'Biryani',
    image: '/images/foods/hyderabadi-dum-chicken-biryani.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Royal Mutton Dum Biryani',
    description: 'Tender baby lamb cuts cooked in traditional earthenware handi with Basmati rice, kewra water, and whole pot spices.',
    price: 410,
    category: 'Biryani',
    image: '/images/foods/royal-mutton-dum-biryani.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Lucknowi Paneer & Veg Biryani',
    description: 'Garden fresh vegetables, paneer cubes, and saffron rice cooked in Awadhi dum style served with cool cucumber raita.',
    price: 250,
    category: 'Biryani',
    image: '/images/foods/lucknowi-paneer-veg-biryani.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.6,
  },
  {
    name: 'Egg Dum Biryani',
    description: 'Golden fried boiled eggs nestled in layered spicy biryani rice with caramelized shallots and mint leaves.',
    price: 260,
    category: 'Biryani',
    image: '/images/foods/egg-dum-biryani.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Medium',
    isPopular: false,
    rating: 4.5,
  },
  {
    name: 'Kolkata Chicken Biryani with Potato & Egg',
    description: 'Aromatic light Basmati rice subtly flavored with meetha attar and saffron, accompanied by soft spiced potato and boiled egg.',
    price: 330,
    category: 'Biryani',
    image: '/images/foods/kolkata-chicken-biryani-with-potato-egg.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Ambur Star Mutton Biryani',
    description: 'Traditional Tamil-Karnataka style biryani cooked with fragrant Seeraga Samba short rice, tender lamb, and curd masala.',
    price: 420,
    category: 'Biryani',
    image: '/images/foods/ambur-star-mutton-biryani.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Spicy',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Chettinad Chicken Biryani',
    description: 'Fiery South Indian biryani infused with star anise, stone flower (kalpasi), black pepper, and bone-in countryside chicken.',
    price: 340,
    category: 'Biryani',
    image: '/images/foods/chettinad-chicken-biryani.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Spicy',
    isPopular: false,
    rating: 4.8,
  },
  {
    name: 'Mushroom & Green Peas Dum Biryani',
    description: 'Button mushrooms and fresh sweet peas cooked with caramelized onions, aromatic mint, and basmati rice.',
    price: 260,
    category: 'Biryani',
    image: '/images/foods/mushroom-green-peas-dum-biryani.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Medium',
    isPopular: false,
    rating: 4.6,
  },
  {
    name: 'Tawa Chicken Tikka Biryani',
    description: 'Street-style spicy tawa-tossed Basmati rice with shredded tandoori tikka, fresh lime juice, and chaat masala.',
    price: 310,
    category: 'Biryani',
    image: '/images/foods/tawa-chicken-tikka-biryani.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Spicy',
    isPopular: false,
    rating: 4.7,
  },
  {
    name: 'Saffron Jeera Rice with Dal Makhani',
    description: 'Aromatic aged Basmati rice tossed with roasted cumin seeds and desi ghee, paired with slow-simmered rich black dal.',
    price: 240,
    category: 'Biryani',
    image: '/images/foods/saffron-jeera-rice-with-dal-makhani.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.7,
  },

  // ==========================================
  // --- 4. CHINESE (10 DISHES) ---
  // ==========================================
  {
    name: 'Dragon Chicken Bangalore Style',
    description: 'Crispy fried chicken strips tossed with cashew nuts, dried red chillies, dark soya sauce, and sweet chilli glaze.',
    price: 310,
    category: 'Chinese',
    image: '/images/foods/dragon-chicken-bangalore-style.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Spicy',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Gobi Manchurian Dry',
    description: 'Bangalore street classic: batter-fried cauliflower florets wok-tossed with ginger, garlic, green chillies, and cilantro.',
    price: 210,
    category: 'Chinese',
    image: '/images/foods/gobi-manchurian-dry.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.7,
  },
  {
    name: 'Chilli Garlic Veg Hakka Noodles',
    description: 'Thin wheat noodles wok-tossed on high flame with shredded bell peppers, cabbage, burnt garlic, and spicy scallion oil.',
    price: 230,
    category: 'Chinese',
    image: '/images/foods/chilli-garlic-veg-hakka-noodles.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Medium',
    isPopular: false,
    rating: 4.6,
  },
  {
    name: 'Schezwan Chicken Fried Rice',
    description: 'Aromatic jasmine rice tossed in house-made fiery Sichuan pepper paste with diced tender chicken, eggs, and spring onion.',
    price: 260,
    category: 'Chinese',
    image: '/images/foods/schezwan-chicken-fried-rice.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Spicy',
    isPopular: false,
    rating: 4.7,
  },
  {
    name: 'Chilli Paneer Gravy',
    description: 'Crisp-coated cottage cheese cubes simmered in a dark soya, green chilli, and garlic gravy with bell pepper chunks.',
    price: 250,
    category: 'Chinese',
    image: '/images/foods/chilli-paneer-gravy.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Spicy',
    isPopular: true,
    rating: 4.7,
  },
  {
    name: 'Chicken Manchurian Gravy',
    description: 'Minced spiced chicken meatballs braised in a savory ginger, garlic, coriander stem, and soya broth.',
    price: 280,
    category: 'Chinese',
    image: '/images/foods/chicken-manchurian-gravy.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Veg Triple Schezwan Fried Rice',
    description: 'Wholesome platter of fiery Schezwan fried rice, crisp fried noodles, and hot Schezwan vegetable gravy.',
    price: 260,
    category: 'Chinese',
    image: '/images/foods/veg-triple-schezwan-fried-rice.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Spicy',
    isPopular: false,
    rating: 4.7,
  },
  {
    name: 'Crispy Honey Chilli Potatoes',
    description: 'Double-fried potato batons tossed in a sweet-and-spicy honey chilli sauce, garnished with toasted white sesame seeds.',
    price: 200,
    category: 'Chinese',
    image: '/images/foods/crispy-honey-chilli-potatoes.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.6,
  },
  {
    name: 'Chicken Hakka Noodles Special',
    description: 'Street-style wok-tossed noodles with chicken shreds, fried egg ribbons, crunchy carrots, and light soya vinegar dressing.',
    price: 260,
    category: 'Chinese',
    image: '/images/foods/chicken-hakka-noodles-special.jpg',
    isAvailable: true,
    isVeg: false,
    spiceLevel: 'Medium',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Crispy Veg Spring Rolls (6 Pcs)',
    description: 'Delicate pastry sheets hand-rolled with julienned Asian vegetables and glass noodles, served with sweet chilli dip.',
    price: 210,
    category: 'Chinese',
    image: '/images/foods/crispy-veg-spring-rolls-6-pcs.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.5,
  },

  // ==========================================
  // --- 5. DESSERTS (8 DISHES) ---
  // ==========================================
  {
    name: 'Gulab Jamun with Shahi Rabdi',
    description: 'Warm, soft mawa dumplings soaked in cardamom sugar syrup, served over a bed of chilled reduced saffron milk.',
    price: 150,
    category: 'Desserts',
    image: '/images/foods/gulab-jamun-with-shahi-rabdi.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Kesari Rasmalai (2 Pcs)',
    description: 'Delicate cottage cheese patties steeped in creamy saffron and pistachio-infused whole milk.',
    price: 160,
    category: 'Desserts',
    image: '/images/foods/kesari-rasmalai-2-pcs.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Gajar Ka Halwa Pure Desi Ghee',
    description: 'Slow-simmered winter red carrots with khoya, crushed almonds, pistachios, and pure cow ghee.',
    price: 150,
    category: 'Desserts',
    image: '/images/foods/gajar-ka-halwa-pure-desi-ghee.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.7,
  },
  {
    name: 'Shahi Tukda Royal Oudh',
    description: 'Crisp ghee-fried bread triangles dipped in saffron syrup, coated with condensed rabdi, silver varq, and pistachios.',
    price: 160,
    category: 'Desserts',
    image: '/images/foods/shahi-tukda-royal-oudh.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Moong Dal Halwa Desi Ghee',
    description: 'Rich, golden yellow split green gram pudding slow-roasted in pure cow ghee and fragrant green cardamom.',
    price: 170,
    category: 'Desserts',
    image: '/images/foods/moong-dal-halwa-desi-ghee.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.9,
  },
  {
    name: 'Kulfi Falooda Delight',
    description: 'Authentic malai kulfi slices topped with sweet basil seeds, cornstarch vermicelli, and pure rose water syrup.',
    price: 150,
    category: 'Desserts',
    image: '/images/foods/kulfi-falooda-delight.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Matka Phirni Chilled',
    description: 'Creamy ground basmati rice pudding slow-simmered in milk, set in an earthenware matka and chilled with slivered nuts.',
    price: 130,
    category: 'Desserts',
    image: '/images/foods/matka-phirni-chilled.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.7,
  },
  {
    name: 'Hot Chocolate Brownie with Fudge',
    description: 'Warm walnut chocolate brownie smothered with hot dark chocolate ganache and chocolate chips.',
    price: 180,
    category: 'Desserts',
    image: '/images/foods/hot-chocolate-brownie-with-fudge.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.8,
  },

  // ==========================================
  // --- 6. BEVERAGES (9 DISHES) ---
  // ==========================================
  {
    name: 'Bangalore Degree Filter Coffee',
    description: 'Traditional decoction brewed with freshly roasted Chikmagalur coffee beans, frothed with hot rich milk in brass dabarah.',
    price: 70,
    category: 'Beverages',
    image: '/images/foods/bangalore-degree-filter-coffee.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Alphonso Mango Malai Lassi',
    description: 'Thick, creamy churned curd blended with Ratnagiri Alphonso mango pulp and topped with saffron strands and pistachios.',
    price: 120,
    category: 'Beverages',
    image: '/images/foods/alphonso-mango-malai-lassi.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Fresh Nimbu Soda (Sweet & Salt)',
    description: 'Freshly squeezed Indian lemon juice with crushed ice and sparkling soda, balanced with rock salt and mint.',
    price: 80,
    category: 'Beverages',
    image: '/images/foods/fresh-nimbu-soda-sweet-salt.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.5,
  },
  {
    name: 'Masala Chai Cutting Kulhad',
    description: 'Strong, fragrant roadside tea brewed with freshly crushed ginger, green cardamom, cinnamon, and cloves in earthen kulhad.',
    price: 60,
    category: 'Beverages',
    image: '/images/foods/masala-chai-cutting-kulhad.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.9,
  },
  {
    name: 'Classic Sweet Punjabi Lassi',
    description: 'Thick churned creamy curd served in a tall glass topped with a rich layer of fresh malai and crushed almonds.',
    price: 100,
    category: 'Beverages',
    image: '/images/foods/classic-sweet-punjabi-lassi.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.8,
  },
  {
    name: 'Spiced Butter Milk (Masala Chaas)',
    description: 'Cool refreshing buttermilk tempered with ginger, green chillies, fresh coriander, curry leaves, and roasted cumin.',
    price: 60,
    category: 'Beverages',
    image: '/images/foods/spiced-butter-milk-masala-chaas.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.7,
  },
  {
    name: 'Cold Badam Milk with Kesar',
    description: 'Chilled rich dairy milk blended with California almond paste, Kashmiri saffron strands, and crushed pistachios.',
    price: 110,
    category: 'Beverages',
    image: '/images/foods/cold-badam-milk-with-kesar.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: true,
    rating: 4.8,
  },
  {
    name: 'Virgin Mojito Cooler',
    description: 'Zesty lime wedges and garden-fresh mint leaves muddled with cane sugar, crushed ice, and sparkling lemon soda.',
    price: 110,
    category: 'Beverages',
    image: '/images/foods/virgin-mojito-cooler.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.6,
  },
  {
    name: 'Kashmiri Kahwa Green Tea',
    description: 'Exotic traditional green tea slow-simmered with whole saffron, green cardamom pods, cinnamon, and slivered almonds.',
    price: 90,
    category: 'Beverages',
    image: '/images/foods/kashmiri-kahwa-green-tea.jpg',
    isAvailable: true,
    isVeg: true,
    spiceLevel: 'Mild',
    isPopular: false,
    rating: 4.7,
  },
];

const users = [
  {
    name: 'Spice Garden Admin',
    email: 'admin@spicegarden.com',
    phone: '9876543210',
    password: 'Admin@123',
    role: 'admin',
    address: {
      street: '100 Feet Road, 12th Main',
      area: 'Indiranagar',
      landmark: 'Near Metro Station',
      city: 'Bangalore',
      pincode: '560038',
    },
  },
  {
    name: 'Rahul Sharma',
    email: 'rahul@example.com',
    phone: '9845012345',
    password: 'Customer@123',
    role: 'customer',
    address: {
      street: 'Flat 402, Green Glen Layout',
      area: 'Bellandur / Koramangala',
      landmark: 'Near Outer Ring Road',
      city: 'Bangalore',
      pincode: '560103',
    },
  },
];

module.exports = { categories, foods, users };
