services:
  - type: web
    name: spice-garden-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: spicegarden_super_secret_jwt_key_2026_blr
      - key: MONGODB_URI
        value: mongodb+srv://Restrarentapp:7pZD2QUvNFxK7PCY@cluster0.zhlwvni.mongodb.net/spice_garden?appName=Cluster0
